-- V15__create_outbox_events.sql
-- Transactional outbox for integration events (ADR-0018, plan 1 slice E2; V15 reserved by TR-X4).
-- A producer inserts one row in the same transaction as its business change, so an event exists
-- if and only if that change commits. A relay (plan 1 slice E3) later hands pending rows to a
-- transport and marks them delivered.
--
-- Generic by design: any event type, source and destination fits without a schema change, and the
-- JSON payload is stored as text because storage never looks inside it.
--
-- Portability: standard SQL only, so it applies on PostgreSQL and the local H2 default (as V13/V14).

CREATE TABLE outbox_events (
    -- Insertion order; the relay orders pending events per key by this column.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- CloudEvents id (ce_id), assigned when recorded and stable across delivery attempts.
    event_id UUID NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    event_source VARCHAR(255) NOT NULL,
    destination VARCHAR(255) NOT NULL,
    -- Aggregate id: partition key and per-key ordering key.
    event_key VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    -- W3C Trace Context of the raising request; NULL when it had no span.
    traceparent VARCHAR(55),
    -- TEXT, not VARCHAR(512): W3C allows up to 32 members of 256-char keys and values, and 512 is only the
    -- size vendors should at least propagate. Trace metadata must never fail the business transaction.
    tracestate TEXT,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Delivery state, owned by the relay (E3).
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_error VARCHAR(2000),
    delivered_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_outbox_events_event_id UNIQUE (event_id),
    CONSTRAINT chk_outbox_events_status CHECK (status IN ('PENDING', 'DELIVERED')),
    CONSTRAINT chk_outbox_events_delivered
        -- IS [NOT] NULL on both branches: a NULL comparison would make a branch UNKNOWN, which a CHECK accepts.
        CHECK ((status = 'DELIVERED' AND delivered_at IS NOT NULL)
            OR (status = 'PENDING' AND delivered_at IS NULL)),
    CONSTRAINT chk_outbox_events_attempts CHECK (attempts >= 0)
);
-- Oldest pending event per key.
CREATE INDEX idx_outbox_events_pending ON outbox_events(status, event_key, id);
-- Retention purge of delivered events.
CREATE INDEX idx_outbox_events_delivered ON outbox_events(status, delivered_at);
