-- V4__create_catalog_hierarchy_and_products.sql
-- Create categories table
CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    parent_id BIGINT REFERENCES categories(id),
    display_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_categories_parent ON categories(parent_id);
CREATE INDEX idx_categories_code ON categories(code);

-- Alter products table to link category_id
ALTER TABLE products ADD COLUMN category_id BIGINT REFERENCES categories(id);
CREATE INDEX idx_products_category_id ON products(category_id);

-- Seed root categories
INSERT INTO categories (code, name, description, parent_id, display_order, is_active) VALUES
('electronics', 'Electronics', 'Consumer electronics and smart gadgets', NULL, 1, TRUE),
('accessories', 'Accessories', 'Device peripherals and add-on gear', NULL, 2, TRUE);

-- Seed subcategories under electronics
INSERT INTO categories (code, name, description, parent_id, display_order, is_active) VALUES
('audio', 'Audio & Sound', 'Headphones, earbuds, speakers, and sound gear', (SELECT id FROM categories WHERE code = 'electronics'), 1, TRUE),
('wearables', 'Wearable Devices', 'Smartwatches, fitness bands, and wearable tech', (SELECT id FROM categories WHERE code = 'electronics'), 2, TRUE),
('computing', 'Computing & Peripherals', 'Keyboards, mice, and computer essentials', (SELECT id FROM categories WHERE code = 'electronics'), 3, TRUE);

-- Seed subcategories under accessories
INSERT INTO categories (code, name, description, parent_id, display_order, is_active) VALUES
('chargers-cables', 'Power & Cables', 'Fast chargers, cables, and charging hubs', (SELECT id FROM categories WHERE code = 'accessories'), 1, TRUE),
('cases-protection', 'Cases & Protection', 'Protective cases, sleeves, and covers', (SELECT id FROM categories WHERE code = 'accessories'), 2, TRUE),
('mounts-stands', 'Mounts & Stands', 'Laptop and device stands, mounts, and holders', (SELECT id FROM categories WHERE code = 'accessories'), 3, TRUE);

-- Backfill existing products with category_id and update category name
UPDATE products SET 
    category_id = (SELECT id FROM categories WHERE code = 'audio'),
    category = 'Audio & Sound'
WHERE sku = 'NG-EARBUD-01';

UPDATE products SET 
    category_id = (SELECT id FROM categories WHERE code = 'wearables'),
    category = 'Wearable Devices'
WHERE sku = 'NG-WATCH-01';

UPDATE products SET 
    category_id = (SELECT id FROM categories WHERE code = 'audio'),
    category = 'Audio & Sound'
WHERE sku = 'NG-SPEAKER-01';

UPDATE products SET 
    category_id = (SELECT id FROM categories WHERE code = 'chargers-cables'),
    category = 'Power & Cables'
WHERE sku = 'NG-CHARGER-01';

UPDATE products SET 
    category_id = (SELECT id FROM categories WHERE code = 'cases-protection'),
    category = 'Cases & Protection'
WHERE sku = 'NG-CASE-01';

UPDATE products SET 
    category_id = (SELECT id FROM categories WHERE code = 'mounts-stands'),
    category = 'Mounts & Stands'
WHERE sku = 'NG-STAND-01';

-- Seed expanded catalog products
INSERT INTO products (sku, name, price, stock_qty, description, category, category_id, is_active) VALUES
('NG-HEADPHONE-01', 'Nova Over-Ear ANC Headphones', 129.90, 45, 'Premium over-ear headphones with ANC and 40-hour battery life.', 'Audio & Sound', (SELECT id FROM categories WHERE code = 'audio'), TRUE),
('NG-BAND-01', 'Nova Fitness Tracker Band', 39.90, 110, 'Lightweight fitness band with heart rate tracking and sleep analysis.', 'Wearable Devices', (SELECT id FROM categories WHERE code = 'wearables'), TRUE),
('NG-KEYBOARD-01', 'Nova Tenkeyless Mechanical Keyboard', 79.90, 75, 'Compact mechanical keyboard with hot-swappable switches and RGB backlighting.', 'Computing & Peripherals', (SELECT id FROM categories WHERE code = 'computing'), TRUE),
('NG-MOUSE-01', 'Nova Wireless Ergonomic Mouse', 29.90, 90, 'Ergonomic wireless mouse with precision optical sensor and silent clicks.', 'Computing & Peripherals', (SELECT id FROM categories WHERE code = 'computing'), TRUE),
('NG-CHARGER-02', 'Nova 100W 4-Port GaN Desktop Charger', 49.90, 60, 'High-power 100W GaN charging station with 3 USB-C and 1 USB-A ports.', 'Power & Cables', (SELECT id FROM categories WHERE code = 'chargers-cables'), TRUE),
('NG-BANK-01', 'Nova MagSafe Magnetic Power Bank 10000mAh', 44.90, 85, 'Snap-on magnetic wireless power bank with 10000mAh capacity and USB-C PD.', 'Power & Cables', (SELECT id FROM categories WHERE code = 'chargers-cables'), TRUE);
