-- CREATE TABLE assistant_sessions (
--     id VARCHAR(64) PRIMARY KEY,
--     user_id VARCHAR(64) NOT NULL,
--     customer_id BIGINT,
--     status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
--     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     version BIGINT NOT NULL DEFAULT 0
-- );

CREATE TABLE assistant_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- session_id VARCHAR(64) NOT NULL REFERENCES assistant_sessions(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL,
    content TEXT,
    widget_type VARCHAR(64),
    widget_payload TEXT,
    tool_call_id VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TABLE assistant_order_drafts (
--     id VARCHAR(64) PRIMARY KEY,
--     session_id VARCHAR(64) NOT NULL REFERENCES assistant_sessions(id) ON DELETE CASCADE,
--     customer_id BIGINT NOT NULL,
--     status VARCHAR(32) NOT NULL DEFAULT 'WAITING_CONFIRMATION',
--     items TEXT NOT NULL,
--     total_amount NUMERIC(12, 2) NOT NULL,
--     expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
--     confirmed_order_number VARCHAR(64),
--     created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     version BIGINT NOT NULL DEFAULT 0
-- );

-- CREATE INDEX idx_assistant_sessions_user ON assistant_sessions(user_id, status);
-- CREATE INDEX idx_assistant_messages_session ON assistant_messages(session_id, created_at);
-- CREATE INDEX idx_assistant_drafts_session ON assistant_order_drafts(session_id, status);
-- CREATE INDEX idx_assistant_drafts_expiry ON assistant_order_drafts(status, expires_at);
