# shellcheck shell=bash
# Shared settings for scripts/k8s/*.sh. Source it; don't run it.
# Every kubectl call targets the kind context explicitly, so other clusters in the kubeconfig are never touched.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
K8S_DIR="$REPO_ROOT/deploy/k8s"
# shellcheck source=SCRIPTDIR/../../deploy/k8s/versions.env
source "$K8S_DIR/versions.env"

KIND_CLUSTER_NAME="${KIND_CLUSTER_NAME:-polaris}"
KIND_CONFIG="${KIND_CONFIG:-$K8S_DIR/kind/cluster.yaml}"
K8S_OVERLAY="${K8S_OVERLAY:-$K8S_DIR/overlays/local}"
K8S_NAMESPACE="${K8S_NAMESPACE:-polaris}"
KUBE_CONTEXT="kind-$KIND_CLUSTER_NAME"

# Edge (K3): third-party components from deploy/k8s/platform, and the Gateway in base/edge. NGINX Gateway Fabric
# names the data-plane Service <gateway>-<gatewayclass>; platform/coredns rewrites *.polaris.local to it.
# shellcheck disable=SC2034 # used by the scripts that source this file
{
  PLATFORM_DIR="$K8S_DIR/platform"
  GATEWAY_NAME=polaris
  GATEWAY_SERVICE="$GATEWAY_NAME-nginx"
  CA_BUNDLE=polaris-ca-bundle
  EDGE_HOSTS=(polaris.local id.polaris.local grafana.polaris.local)
}
# Upper bound for each Helm install or readiness wait, so a stuck component fails the run instead of hanging it.
K8S_WAIT_TIMEOUT="${K8S_WAIT_TIMEOUT:-300s}"

# Pinned tools are installed here by scripts/k8s/tools.sh and take precedence over anything on PATH.
TOOLS_BIN="${TOOLS_BIN:-$REPO_ROOT/.tools/bin}"
export PATH="$TOOLS_BIN:$PATH"

log() { printf '[k8s] %s\n' "$*" >&2; }
die() {
  log "ERROR: $*"
  exit 1
}

ensure_tools() { "$REPO_ROOT/scripts/k8s/tools.sh" "$@"; }

kctl() { kubectl --context "$KUBE_CONTEXT" "$@"; }

sha256() {
  if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1; else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

cluster_exists() { kind get clusters 2>/dev/null | grep -qx "$KIND_CLUSTER_NAME"; }

# Application images (TR-K2): $IMAGE_REGISTRY/<app>:<git-sha>, never `latest`. CI pushes them to GHCR on main
# (.github/workflows/images.yml); `make k8s-images` builds them locally and loads them into kind. A fork sets
# IMAGE_REGISTRY to its own ghcr.io/<owner>; it is lowercased because registry repository names must be.
APPS=(polaris polaris-assistant polaris-fulfilment-emulator)
IMAGE_REGISTRY="$(printf '%s' "${IMAGE_REGISTRY:-ghcr.io/vungdv}" | tr '[:upper:]' '[:lower:]')"
IMAGE_TAG="${IMAGE_TAG:-$(git -C "$REPO_ROOT" rev-parse HEAD)}"
IMAGE_PINS="$K8S_DIR/overlays/local/images/kustomization.yaml"

app_image() { printf '%s/%s:%s' "$IMAGE_REGISTRY" "$1" "$IMAGE_TAG"; }

# Writes the untracked Kustomize component that pins the local overlay's app images to IMAGE_TAG (the git SHA), so the
# tag follows the checkout without a committed value to bump on every commit. Base manifests name each image by its
# app name (`image: polaris`); the component maps it to $IMAGE_REGISTRY/<app>:<sha>.
write_image_pins() {
  local app
  mkdir -p "$(dirname "$IMAGE_PINS")"
  {
    printf '# Generated by scripts/k8s/lib.sh (write_image_pins) from the git HEAD. Untracked; do not edit.\n'
    printf 'apiVersion: kustomize.config.k8s.io/v1alpha1\nkind: Component\nimages:\n'
    for app in "${APPS[@]}"; do
      printf '  - name: %s\n    newName: %s/%s\n    newTag: "%s"\n' "$app" "$IMAGE_REGISTRY" "$app" "$IMAGE_TAG"
    done
  } >"$IMAGE_PINS"
}
