# shellcheck shell=bash
# Shared settings for scripts/k8s/*.sh. Source it; don't run it.
# Every kubectl call targets the kind context explicitly, in a repo-local kubeconfig (K8S_KUBECONFIG), so the user's
# ~/.kube/config and its current context are never read or rewritten.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
K8S_DIR="$REPO_ROOT/deploy/k8s"
# shellcheck source=SCRIPTDIR/../../deploy/k8s/versions.env
source "$K8S_DIR/versions.env"

KIND_CLUSTER_NAME="${KIND_CLUSTER_NAME:-polaris}"
KIND_CONFIG="${KIND_CONFIG:-$K8S_DIR/kind/cluster.yaml}"
K8S_OVERLAY="${K8S_OVERLAY:-$K8S_DIR/overlays/local}"
K8S_NAMESPACE="${K8S_NAMESPACE:-polaris}"
KUBE_CONTEXT="kind-$KIND_CLUSTER_NAME"
# kind writes the cluster's credentials here (--kubeconfig), and kubectl and helm read them from here (KUBECONFIG).
K8S_KUBECONFIG="${K8S_KUBECONFIG:-$REPO_ROOT/.tools/kubeconfig}"
[[ "$K8S_KUBECONFIG" = /* ]] || K8S_KUBECONFIG="$REPO_ROOT/$K8S_KUBECONFIG" # a relative override is repo-relative
export KUBECONFIG="$K8S_KUBECONFIG"

# Edge (K3): third-party components from deploy/k8s/platform, and the Gateway in base/edge. NGINX Gateway Fabric
# names the data-plane Service <gateway>-<gatewayclass>; platform/coredns rewrites *.polaris.local to it.
# shellcheck disable=SC2034 # used by the scripts that source this file
{
  PLATFORM_DIR="$K8S_DIR/platform"
  GATEWAY_NAME=polaris
  GATEWAY_SERVICE="$GATEWAY_NAME-nginx"
  CA_BUNDLE=polaris-ca-bundle
  EDGE_HOSTS=(polaris.local id.polaris.local grafana.polaris.local)
  # Observability (K4): the Collector (Deployment and Service) in the app namespace, the log agent (DaemonSet) in its
  # own namespace (platform/otel-agent).
  OTEL_COLLECTOR=otel-collector
  OTEL_AGENT=otel-agent
  OTEL_AGENT_NAMESPACE=observability
  # Data stores (K5): the CloudNativePG operator in its own namespace (platform/cloudnative-pg), one PostgreSQL Cluster
  # per owner and Redis in the app namespace (base/data, base/redis).
  CNPG_RELEASE=cloudnative-pg
  CNPG_NAMESPACE=cnpg-system
  PG_CLUSTERS=(polaris-db keycloak-db)
  REDIS=redis
  # Kafka (K6): the Strimzi cluster operator in its own namespace (platform/strimzi), and the Kafka cluster with its
  # node pool in the app namespace (base/kafka). Strimzi names the pods <cluster>-<pool>-<node id> and the bootstrap
  # Service <cluster>-kafka-bootstrap.
  STRIMZI_RELEASE=strimzi
  STRIMZI_NAMESPACE=strimzi
  KAFKA_CLUSTER=kafka
  KAFKA_NODE_POOL=dual-role
  KAFKA_BOOTSTRAP="$KAFKA_CLUSTER-kafka-bootstrap:9092"
  # Identity (K7): the Keycloak Operator and its Keycloak in the app namespace (platform/keycloak-operator,
  # base/keycloak). The operator names the server's StatefulSet <keycloak> and its Service <keycloak>-service, and the
  # bootstrap admin's Secret <keycloak>-initial-admin. The realm placeholders (DEFAULT_PASSWORD and
  # POLARIS_FULFILMENT_EMULATOR_SECRET, the keys of .env.template / Compose) live in KEYCLOAK_REALM_SECRET.
  KEYCLOAK=keycloak
  KEYCLOAK_OPERATOR=keycloak-operator
  KEYCLOAK_REALM_SECRET=keycloak-realm-placeholders
  KEYCLOAK_REALM_IMPORTS=(polaris-realm)
  REALM_DIR="$REPO_ROOT/docker/keycloak"
  REALM_COMPONENT="$K8S_DIR/overlays/local/realms"
  # Order & Catalog (K8): Deployment, Service and HTTPRoutes `polaris` (base/polaris), and Swagger UI (base/swagger-ui).
  POLARIS=polaris
  SWAGGER_UI=swagger-ui
  # Assistant (K9): Deployment, Service and HTTPRoutes `polaris-assistant` (base/polaris-assistant), and its Secret of the
  # same name, generated by up.sh from ASSISTANT_SECRET_KEYS in the untracked env file (the keys of .env.template).
  ASSISTANT=polaris-assistant
  ASSISTANT_SECRET=polaris-assistant
  ASSISTANT_SECRET_KEYS=(GEMINI_API_KEY TYPESAFE_API_KEY AGENTO11Y_PROTOCOL AGENTO11Y_ENDPOINT AGENTO11Y_AUTH_MODE
    AGENTO11Y_AUTH_TENANT_ID AGENTO11Y_AUTH_TOKEN)
  # Fulfilment (K10): Deployment and Service `polaris-fulfilment-emulator` (base/polaris-fulfilment-emulator), one Kafka
  # consumer group per partner (EMULATOR_GROUP_PREFIX<partner>). Its client secret is POLARIS_FULFILMENT_EMULATOR_SECRET
  # in KEYCLOAK_REALM_SECRET.
  EMULATOR=polaris-fulfilment-emulator
  EMULATOR_GROUP_PREFIX=fulfilment.
  EMULATOR_PARTNERS=(partner-north partner-central partner-south)
  # Hardening (K11): CNPG backups through the Barman Cloud plugin (next to the CNPG operator, platform/barman-cloud) to
  # the bucket BACKUP_BUCKET on the in-cluster object store (SeaweedFS all-in-one in its own namespace,
  # platform/object-store), with the S3 credentials in Secret OBJECT_STORE_CREDENTIALS (base/data/backup.yaml).
  BARMAN_CLOUD_RELEASE=barman-cloud
  OBJECT_STORE_RELEASE=seaweedfs
  OBJECT_STORE_NAMESPACE=object-store
  OBJECT_STORE_DEPLOYMENT=seaweedfs-all-in-one
  OBJECT_STORE_CREDENTIALS=object-store-credentials
  BACKUP_BUCKET=cnpg-backups
  # The kind worker (kind/cluster.yaml) runs only the replicated stateless apps; the smoke test drains it.
  STATELESS_POOL_LABEL=polaris.local/pool=stateless-apps
}
# kafka_pod <node id>: the pod name of a Kafka node.
kafka_pod() { printf '%s-%s-%s' "$KAFKA_CLUSTER" "$KAFKA_NODE_POOL" "$1"; }
# Untracked env file with the keys of .env.template (TR-K3): the source of the cluster's Secrets (GRAFANA_CLOUD_* for
# K4, DEFAULT_PASSWORD and POLARIS_FULFILMENT_EMULATOR_SECRET for K7, the assistant's keys for K9). Optional: a missing
# key keeps each component's documented default.
K8S_ENV_FILE="${K8S_ENV_FILE:-$K8S_DIR/.env.local}"
# env_value <key>: the value of `<key>=<value>` in the untracked env file (the last one wins), or nothing. The file is
# read as data, never sourced.
env_value() { if [ -f "$K8S_ENV_FILE" ]; then sed -n "s/^$1=//p" "$K8S_ENV_FILE" | tail -n 1; fi; }
# Upper bound for each Helm install or readiness wait, so a stuck component fails the run instead of hanging it.
K8S_WAIT_TIMEOUT="${K8S_WAIT_TIMEOUT:-300s}"

# Pinned tools are installed here by scripts/k8s/tools.sh and take precedence over anything on PATH.
TOOLS_BIN="${TOOLS_BIN:-$REPO_ROOT/.tools/bin}"
export PATH="$TOOLS_BIN:$PATH"

log() { printf '[k8s] %s\n' "$*" >&2; }
die() {
  log "ERROR: $*"
  exit 1
}

ensure_tools() { "$REPO_ROOT/scripts/k8s/tools.sh" "$@"; }

kctl() { kubectl --context "$KUBE_CONTEXT" "$@"; }

# retry <attempts> <command...>: runs the command until it succeeds, with exponential backoff (2s, 4s, 8s, ...).
# For calls that race a component's readiness, such as an admission webhook whose Pod is Ready before its serving
# certificate is injected.
retry() {
  local attempts="$1" delay=2 n=1
  shift
  until "$@"; do
    [ "$n" -lt "$attempts" ] || return 1
    log "attempt $n/$attempts failed, retrying in ${delay}s: $*"
    sleep "$delay"
    n=$((n + 1))
    delay=$((delay * 2))
  done
}

# secret_key <namespace> <secret> <key>: the decoded value of one key of a Secret, or nothing when it doesn't exist.
secret_key() {
  kctl -n "$1" get secret "$2" -o jsonpath="{.data.$3}" 2>/dev/null | base64 -d 2>/dev/null || true
}

sha256() {
  if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1; else shasum -a 256 "$1" | cut -d' ' -f1; fi
}

cluster_exists() { kind get clusters 2>/dev/null | grep -qx "$KIND_CLUSTER_NAME"; }

# Rewrites the kubeconfig entry of an existing cluster from kind, so a deleted file or stale credentials (the cluster
# was recreated from another worktree or by hand) never survive. Cheap and idempotent.
ensure_kubeconfig() {
  log "writing the kubeconfig of cluster '$KIND_CLUSTER_NAME' to $K8S_KUBECONFIG"
  kind export kubeconfig --name "$KIND_CLUSTER_NAME" --kubeconfig "$K8S_KUBECONFIG"
}

# Application images (TR-K2): $IMAGE_REGISTRY/<app>:<git-sha>, never `latest`. CI pushes them to GHCR on main
# (.github/workflows/images.yml); `make k8s-images` builds them locally and loads them into kind. A fork sets
# IMAGE_REGISTRY to its own ghcr.io/<owner>; it is lowercased because registry repository names must be.
APPS=(polaris polaris-assistant polaris-fulfilment-emulator)
IMAGE_REGISTRY="$(printf '%s' "${IMAGE_REGISTRY:-ghcr.io/vungdv}" | tr '[:upper:]' '[:lower:]')"
IMAGE_TAG="${IMAGE_TAG:-$(git -C "$REPO_ROOT" rev-parse HEAD)}"
IMAGE_PINS="$K8S_DIR/overlays/local/images/kustomization.yaml"

app_image() { printf '%s/%s:%s' "$IMAGE_REGISTRY" "$1" "$IMAGE_TAG"; }

# image_loaded <image>: whether the kind node already holds the image (loaded by `make k8s-images`).
image_loaded() { docker exec "$KIND_CLUSTER_NAME-control-plane" crictl inspecti "$1" >/dev/null 2>&1; }

# Writes the untracked Kustomize component that pins the local overlay's app images to IMAGE_TAG (the git SHA), so the
# tag follows the checkout without a committed value to bump on every commit. Base manifests name each image by its
# app name (`image: polaris`); the component maps it to $IMAGE_REGISTRY/<app>:<sha>.
write_image_pins() {
  local app
  mkdir -p "$(dirname "$IMAGE_PINS")"
  {
    printf '# Generated by scripts/k8s/lib.sh (write_image_pins) from the git HEAD. Untracked; do not edit.\n'
    printf 'apiVersion: kustomize.config.k8s.io/v1alpha1\nkind: Component\nimages:\n'
    for app in "${APPS[@]}"; do
      printf '  - name: %s\n    newName: %s/%s\n    newTag: "%s"\n' "$app" "$IMAGE_REGISTRY" "$app" "$IMAGE_TAG"
    done
  } >"$IMAGE_PINS"
}

# stage_keycloak_operator <dir>: copies platform/keycloak-operator into <dir> and downloads the Keycloak Operator's
# upstream release manifests (the two CRDs and kubernetes.yml at KEYCLOAK_VERSION) next to it, each verified against
# its pinned SHA-256 (TR-K1: nothing upstream is copied into the repo). <dir> is then a complete kustomization.
stage_keycloak_operator() {
  local dir="$1" file sum
  local base="https://github.com/keycloak/keycloak-k8s-resources/raw/refs/tags/$KEYCLOAK_VERSION/kubernetes"
  mkdir -p "$dir"
  cp "$PLATFORM_DIR/keycloak-operator/"*.yaml "$dir/"
  for file in keycloaks.k8s.keycloak.org-v1.yml:"$KEYCLOAK_CRD_SHA256" \
    keycloakrealmimports.k8s.keycloak.org-v1.yml:"$KEYCLOAK_REALM_IMPORT_CRD_SHA256" \
    kubernetes.yml:"$KEYCLOAK_OPERATOR_SHA256"; do
    sum="${file#*:}"
    file="${file%%:*}"
    curl -fsSL --retry 3 --max-time 60 -o "$dir/$file" "$base/$file"
    [ "$(sha256 "$dir/$file")" = "$sum" ] || die "checksum mismatch for Keycloak Operator $KEYCLOAK_VERSION $file"
  done
}

# Writes the untracked Kustomize component (REALM_COMPONENT) that imports the realms of docker/keycloak, the single
# source shared with Compose, so no copy is committed:
#   - polaris-realm.json as a KeycloakRealmImport. The CRD takes the realm inline (spec.realm), so the file is embedded
#     as is. Its ${DEFAULT_PASSWORD} and ${POLARIS_FULFILMENT_EMULATOR_SECRET} stay placeholders: the operator's import
#     Job resolves them from the Secret KEYCLOAK_REALM_SECRET (spec.placeholders), as Compose resolves them from .env.
#   - master-realm.json as the ConfigMap keycloak-master-realm, which the Keycloak server imports at its first start
#     (base/keycloak/keycloak.yaml explains why the master realm can't be a KeycloakRealmImport).
# JSON is valid manifest input for kubectl and Kustomize, so jq builds both resources without a YAML conversion.
write_realm_imports() {
  command -v jq >/dev/null || die "jq is required to generate the Keycloak realm imports"
  mkdir -p "$REALM_COMPONENT"
  printf '%s\n' "# Generated by scripts/k8s/lib.sh (write_realm_imports) from docker/keycloak. Untracked; do not edit." \
    'apiVersion: kustomize.config.k8s.io/v1alpha1' 'kind: Component' 'resources:' \
    '  - master-realm.configmap.json' '  - polaris-realm.realmimport.json' >"$REALM_COMPONENT/kustomization.yaml"
  jq -n --rawfile realm "$REALM_DIR/master-realm.json" --arg ns "$K8S_NAMESPACE" '{
    apiVersion: "v1", kind: "ConfigMap",
    metadata: {name: "keycloak-master-realm", namespace: $ns, labels: {"app.kubernetes.io/name": "keycloak", "app.kubernetes.io/part-of": "polaris"}},
    data: {"master-realm.json": $realm}
  }' >"$REALM_COMPONENT/master-realm.configmap.json"
  jq -n --slurpfile realm "$REALM_DIR/polaris-realm.json" --arg secret "$KEYCLOAK_REALM_SECRET" --arg kc "$KEYCLOAK" --arg ns "$K8S_NAMESPACE" '{
    apiVersion: "k8s.keycloak.org/v2alpha1", kind: "KeycloakRealmImport",
    metadata: {name: "polaris-realm", namespace: $ns, labels: {"app.kubernetes.io/name": "keycloak", "app.kubernetes.io/part-of": "polaris"}},
    spec: {
      keycloakCRName: $kc,
      placeholders: ({} | .DEFAULT_PASSWORD = {secret: {name: $secret, key: "DEFAULT_PASSWORD"}}
        | .POLARIS_FULFILMENT_EMULATOR_SECRET = {secret: {name: $secret, key: "POLARIS_FULFILMENT_EMULATOR_SECRET"}}),
      realm: $realm[0]
    }
  }' >"$REALM_COMPONENT/polaris-realm.realmimport.json"
}
