package vn.danang.polaris.assistant.ai;

import java.util.Collections;
import java.util.List;

/**
 * Represents the response from an AI Foundation Model.
 * May contain textual completion and/or a list of requested tool calls.
 *
 * @param text the textual reply generated by the model
 * @param toolCalls any tool calls proposed by the model
 * @param thoughtSignature the opaque thought signature returned by the model
 * @param modelCall the provider call that produced this response, or null for a local fallback reply
 */
public record ModelResponse(
        String text,
        List<ToolCall> toolCalls,
        String thoughtSignature,
        ModelCall modelCall
) implements ModelCallResult {
    public ModelResponse(String text) {
        this(text, List.of(), null);
    }

    public ModelResponse(String text, List<ToolCall> toolCalls) {
        this(text, toolCalls, null);
    }

    public ModelResponse(String text, List<ToolCall> toolCalls, String thoughtSignature) {
        this(text, toolCalls, thoughtSignature, null);
    }

    public ModelResponse withModelCall(ModelCall modelCall) {
        return new ModelResponse(text, toolCalls, thoughtSignature, modelCall);
    }

    @Override
    public List<ToolCall> toolCalls() {
        return toolCalls != null ? toolCalls : Collections.emptyList();
    }

    public boolean hasToolCalls() {
        return toolCalls != null && !toolCalls.isEmpty();
    }
}
