package vn.danang.polaris.assistant.ai;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * Represents a tool call requested by the AI Foundation Model.
 *
 * @param id the unique identifier of the tool call, if provided by the model
 * @param name the unique name of the tool to execute
 * @param args the arguments map to pass to the tool
 * @param thoughtSignature the opaque thought signature generated by the model for this call
 */
public record ToolCall(
        @JsonProperty("id") String id,
        @JsonProperty("name") String name,
        @JsonProperty("args") @JsonAlias("arguments") Map<String, Object> args,
        @JsonProperty("thoughtSignature") @JsonAlias("thought_signature") String thoughtSignature
) {
    public ToolCall(String name, Map<String, Object> args) {
        this(null, name, args, null);
    }

    public ToolCall(String name, Map<String, Object> args, String thoughtSignature) {
        this(null, name, args, thoughtSignature);
    }

    public ToolCall(String id, String name, Map<String, Object> args) {
        this(id, name, args, null);
    }

    public ToolCall {
        if (args == null) {
            args = Map.of();
        }
    }

    /**
     * Alias for {@link #args()} to preserve backwards compatibility.
     *
     * @return the arguments map
     */
    @JsonIgnore
    public Map<String, Object> arguments() {
        return args;
    }
}
